### ISSUE TITLE
:memo: Documentation for the routes

### ISSUE THREAD

**Issue by 6im0n** [epitech-mirroring/MyTeams#24]
# 👮‍♂️ What's needed
Need a documentation for the all the routes and here description

## 📋 Subtasks
- [x] Login route
- [x] Logout route
- [x] Users route
- [x] User info route
- [x] Send direct message route
- [x] Get all message with user route
- [x] Join team route
- [x] Leave team route
- [x] Get all teams route
- [x] Create team route
- [x] Get teams' users route
- [x] Get teams' channels route
- [x] Create channel route
- [x] Get channels' threads route
- [x] Create thread route
- [x] Get thread messages route
- [x] Reply in thread route

# 📜 Sources
Documentation/routes.md
