### ISSUE TITLE
🎆 Add event loggin for server side

### ISSUE THREAD

**Issue by 6im0n** [epitech-mirroring/MyTeams#60]
# 👮‍♂️ What's needed
Add event login for server

## 📋 Subtasks
- [x] server_event_team_created
- [x] server_event_channel_created
- [x] server_event_thread_created
- [x] server_event_reply_created
- [x] server_event_user_subscribed
- [x] server_event_user_unsubscribed
- [x] server_event_user_created
- [x] server_event_user_loaded
- [x] server_event_user_logged_in
- [x] server_event_user_logged_out
- [x] server_event_private_message_sended

# 📜 Sources
No specific source
